apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1200Gi
  storageClassName: fsx-sc
  volumeMode: Filesystem
  volumeName: fsx-pv-$NAMESPACE
