apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv-$NAMESPACE
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: $FSX_FILESYSTEM_ID
    volumeAttributes:
      dnsname: $FSX_DNS_NAME
      mountname: $FSX_MOUNT_NAME
  storageClassName: fsx-sc
  volumeMode: Filesystem
