apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-lustre-pv-$NAMESPACE
spec:
  capacity:
    storage: ${FSX_LUSTRE_STORAGE_CAPACITY}
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: $FSX_LUSTRE_FILESYSTEM_ID
    volumeAttributes:
      dnsname: $FSX_LUSTRE_DNS_NAME
      mountname: $FSX_LUSTRE_MOUNT_NAME
  storageClassName: fsx-lustre-sc
  volumeMode: Filesystem
