apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-openzfs-pv-$NAMESPACE
spec:
  capacity:
    storage: ${FSX_OPENZFS_STORAGE_CAPACITY}
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: fsx.openzfs.csi.aws.com
    volumeHandle: $FSX_OPENZFS_VOLUME_ID
    volumeAttributes:
      dnsname: $FSX_OPENZFS_DNS_NAME
      mountname: $FSX_OPENZFS_MOUNT_NAME
  storageClassName: fsx-openzfs-sc
  volumeMode: Filesystem
