apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-openzfs-claim
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${FSX_OPENZFS_STORAGE_CAPACITY}
  storageClassName: fsx-openzfs-sc
  volumeMode: Filesystem
  volumeName: fsx-openzfs-pv-$NAMESPACE
