apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-viewer
rules:
  - apiGroups: ["workspace.jupyter.org"]
    resources: ["workspaceaccessstrategies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workspace-viewer-binding
subjects:
  - kind: Group
    name: hyperpod-ds-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: workspace-viewer
  apiGroup: rbac.authorization.k8s.io
